version: '3.8'

services:
  database:
    container_name: finances-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
    - '4306:3306'
    volumes:
    - ./docker/mysql:/var/lib/mysql

  php:
    container_name: finances-php
    build:
      context: ./docker/php
    ports:
    - '9000:9000'
    volumes:
    - .:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: finances-nginx
    image: nginx:stable-alpine
    ports:
    - '8000:80'
    volumes:
    - .:/var/www/symfony_docker
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: [1025, 1080]

