App\Entity\Expenses:
  attributes:
    normalization_context:
      groups: ['expenses_read']
    denormalization_context:
      groups: ['expenses_write']
  itemOperations:
    get: ~
    put: ~
    delete: ~

  collectionOperations:
    get: ~
    post: ~
