App\Entity\User:
  attributes:
    normalization_context:
      groups: ['user_read']
    denormalization_context:
      groups: ['user_write']
  collectionOperations:
    get: ~
    post:
      path: '/register'