App\Entity\UserBalance:
  attributes:
    normalization_context:
      groups: ['balance_read']
    denormalization_context:
      groups: ['balance_write']
  collectionOperations:
    update_balance:
      method: POST
      security: "is_granted('ROLE_USER') or is_granted('ROLE_ADMIN')"
      messenger: input
      path: '/balance/update'
      input: App\Dto\Input\UserBalance\UpdateUserBalanceRequest
      output: App\Entity\UserBalance
      status: 200
    get_personal_report:
      method: GET
      path: '/balance/report'
      output: App\Dto\Output\USerBalance\UserBalanceReportOutput
  itemOperations:
    get:
      security: "object.getOwner() == user"
      path: balance/report/{id}